name: Terraform CI/CD

on:
  push:
    branches:
      - main
      - cicd
  pull_request:

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write
      id-token: write   # required for OIDC with cloud providers
      issues: write

    steps:
      # Checkout repo
      - name: Checkout
        uses: actions/checkout@v4

      # Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5  # pin your version

      # Init
      - name: Terraform Init
        run: terraform init
        working-directory: terraform

      # Format check - Style / formatting
      - name: Terraform Format  
        run: terraform fmt -check
        working-directory: terraform

      # Validate - syntax and internal consistency
      - name: Terraform Validate
        run: terraform validate
        working-directory: terraform

      # Lint - best practices & provider checks
      - name: Terraform Lint
        uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: latest
      - run: tflint --recursive



      # Plan
      - name: Terraform Plan
        run: terraform plan -var-file=env/dev/terraform.tfvars -out=tfplan
        working-directory: terraform

      # Upload Plan as artifact (useful in PRs)
      - name: Upload plan
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: tfplan

  apply:
    name: Terraform Apply
    runs-on: ubuntu-latest
    needs: terraform
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5

      - name: Terraform Init
        run: terraform init
        working-directory: terraform

      - name: Download plan
        uses: actions/download-artifact@v4
        with:
          name: tfplan
          path: .
        

#      - name: Terraform Apply
#        run: terraform apply -auto-approve tfplan
